ln -sf ~/.dotfiles/.oh-my-zsh ~/.oh-my-zsh
ln -sf ~/.dotfiles/.bash_profile ~/.bash_profile
ln -sf ~/.dotfiles/.gitignore ~/.gitignore
ln -sf ~/.dotfiles/.tmux.conf ~/.tmux.conf
ln -sf ~/.dotfiles/.vimrc ~/.vimrc
ln -sf ~/.dotfiles/.vimrc.bundle ~/.vimrc.bundle
ln -sf ~/.dotfiles/.zshrc ~/.zshrc
ln -sf ~/.dotfiles/.templates ~/.templates
ln -sf ~/.dotfiles/.gitconfig ~/.gitconfig
